# Generated by Django 5.2.4 on 2025-07-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('short_code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('long_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
